export const MOVIE_SCHEDULE_REQUEST = "@movieSchedule/MOVIE_SCHEDULE_REQUEST";
export const MOVIE_SCHEDULE_SUCCESS = "@movieSchedule/MOVIE_SCHEDULE_SUCCESS";
export const MOVIE_SCHEDULE_FAILED = "@movieSchedule/MOVIE_SCHEDULE_FAILED";
